erDiagram
    dmp ||--o{ dmp_general_info : "has"
    dmp_general_info ||--o{ dmp_general_info_dmp_id : "has"
    dmp_general_info ||--o{ dmp_general_info_linked_dmp : "has"
    dmp_general_info_linked_dmp ||--o{ dmp_general_info_linked_dmp_linked_dmp_id : "has"
    dmp ||--o{ dmp_contributor : "has"
    dmp_contributor ||--o{ dmp_contributor_contributor_id : "has"
    dmp_contributor ||--o{ dmp_contributor_affiliation : "has"
    dmp_contributor_affiliation ||--o{ dmp_contributor_affiliation_contributor_affiliation_id : "has"
    dmp_contributor_affiliation ||--o{ dmp_contributor_affiliation_contributor_country : "has"
    dmp_contributor_affiliation ||--o{ dmp_contributor_affiliation_contributor_province_state : "has"
    dmp ||--o{ dmp_approval : "has"
    dmp ||--o{ dmp_project : "has"
    dmp_project ||--o{ dmp_project_funding : "has"
    dmp_project_funding ||--o{ dmp_project_funding_source : "has"
    dmp_project_funding ||--o{ dmp_project_funding_funder_id : "has"
    dmp_project_funding ||--o{ dmp_project_funding_grant_id : "has"
    dmp_project ||--o{ dmp_project_partner_organization : "has"
    dmp_project_partner_organization ||--o{ dmp_project_partner_organization_agreement : "has"
    dmp_project_partner_organization ||--o{ dmp_project_partner_organization_partner_organization_id : "has"
    dmp_project ||--o{ dmp_project_safeguarding_science_measures : "has"
    dmp ||--o{ dmp_cost : "has"
    dmp_cost ||--o{ dmp_cost_cost_documentation : "has"
    dmp ||--o{ dmp_indigenous_considerations : "has"
    dmp_indigenous_considerations ||--o{ dmp_indigenous_considerations_community_approval : "has"
    dmp ||--o{ dmp_dataset : "has"
    dmp_dataset ||--o{ dmp_dataset_dataset_id : "has"
    dmp_dataset ||--o{ dmp_dataset_subject : "has"
    dmp_dataset ||--o{ dmp_dataset_dataset_documentation : "has"
    dmp_dataset ||--o{ dmp_dataset_security_and_privacy : "has"
    dmp_dataset_security_and_privacy ||--o{ dmp_dataset_security_and_privacy_privacy_impact_assessment : "has"
    dmp_dataset ||--o{ dmp_dataset_collection : "has"
    dmp_dataset ||--o{ dmp_dataset_technical_resource : "has"
    dmp_dataset_technical_resource ||--o{ dmp_dataset_technical_resource_data_management_system : "has"
    dmp_dataset_technical_resource ||--o{ dmp_dataset_technical_resource_hardware_requirements : "has"
    dmp_dataset_technical_resource ||--o{ dmp_dataset_technical_resource_software : "has"
    dmp_dataset_technical_resource_software ||--o{ dmp_dataset_technical_resource_software_software_management_pla : "has"
    dmp_dataset ||--o{ dmp_dataset_intellectual_property : "has"
    dmp_dataset ||--o{ dmp_dataset_metadata : "has"
    dmp_dataset_metadata ||--o{ dmp_dataset_metadata_metadata_standard_id : "has"
    dmp_dataset ||--o{ dmp_dataset_distribution : "has"
    dmp_dataset_distribution ||--o{ dmp_dataset_distribution_version_history : "has"
    dmp_dataset_distribution ||--o{ dmp_dataset_distribution_geographic_bounding_box : "has"
    dmp_dataset_distribution ||--o{ dmp_dataset_distribution_host : "has"
    dmp_dataset_distribution ||--o{ dmp_dataset_distribution_physical_data_asset : "has"
    dmp_dataset_distribution ||--o{ dmp_dataset_distribution_distribution_id : "has"
    dmp_dataset_distribution ||--o{ dmp_dataset_distribution_online_service : "has"
    dmp_dataset_distribution ||--o{ dmp_dataset_distribution_data_integrity : "has"
    dmp_dataset ||--o{ dmp_dataset_disposition_planning : "has"
    dmp_dataset_disposition_planning ||--o{ dmp_dataset_disposition_planning_retention_specification : "has"
    dmp_dataset_disposition_planning ||--o{ dmp_dataset_disposition_planning_disposition_impediment : "has"
    dmp_dataset ||--o{ dmp_dataset_disposition_action : "has"
    dmp_dataset ||--o{ dmp_dataset_creator : "has"
    dmp_dataset_creator ||--o{ dmp_dataset_creator_affiliation : "has"
    dmp_dataset_creator_affiliation ||--o{ dmp_dataset_creator_affiliation_creator_affiliation_id : "has"
    dmp_dataset_creator_affiliation ||--o{ dmp_dataset_creator_affiliation_creator_country : "has"
    dmp_dataset_creator_affiliation ||--o{ dmp_dataset_creator_affiliation_creator_province_state : "has"
    dmp_dataset_creator ||--o{ dmp_dataset_creator_creator_id : "has"
    dmp ||--o{ dmp_contact : "has"
    dmp_contact ||--o{ dmp_contact_contact_id : "has"
    dmp_contact ||--o{ dmp_contact_affiliation : "has"
    dmp_contact_affiliation ||--o{ dmp_contact_affiliation_contact_affiliation_id : "has"
    dmp_contact_affiliation ||--o{ dmp_contact_affiliation_contact_country : "has"
    dmp_contact_affiliation ||--o{ dmp_contact_affiliation_contact_province_state : "has"
    dmp {
        string id
    }
    dmp_approval {
        string id
        string dmp_id
        string status
        string description
        string by_mbox
    }
    dmp_contact {
        string id
        string dmp_id
        string name
        string mbox
        string role
        string url
        string organization
        string position
        string telephone
        string fax
        string delivery_point
        string city
        string postal_zip_code
        string hours_of_service
    }
    dmp_contact_affiliation {
        string id
        string dmp_contact_id
        string array_index
        string contact_affiliation_name
    }
    dmp_contact_affiliation_contact_affiliation_id {
        string id
        string dmp_contact_affiliation_id
        string registry_uri
        string registry_version
        string type
        string identifier
    }
    dmp_contact_affiliation_contact_country {
        string id
        string dmp_contact_affiliation_id
        string code
        string name
    }
    dmp_contact_affiliation_contact_province_state {
        string id
        string dmp_contact_affiliation_id
        string code
        string name
    }
    dmp_contact_contact_id {
        string id
        string dmp_contact_id
        string identifier
        string type
        string registry_url
        string registry_version
    }
    dmp_contributor {
        string id
        string dmp_id
        string array_index
        string name
        string role
        string mbox
        string position
        string telephone
        string fax
        string delivery_point
        string city
        string postal_zip_code
        string url
        string hours_of_service
    }
    dmp_contributor_affiliation {
        string id
        string dmp_contributor_id
        string array_index
        string contributor_affiliation_name
    }
    dmp_contributor_affiliation_contributor_affiliation_id {
        string id
        string dmp_contributor_affiliation_id
        string identifier
        string type
        string registry_url
        string registry_version
    }
    dmp_contributor_affiliation_contributor_country {
        string id
        string dmp_contributor_affiliation_id
        string name
        string code
    }
    dmp_contributor_affiliation_contributor_province_state {
        string id
        string dmp_contributor_affiliation_id
        string name
        string code
    }
    dmp_contributor_contributor_id {
        string id
        string dmp_contributor_id
        string type
        string registry_url
        string registry_version
        string identifier
    }
    dmp_cost {
        string id
        string dmp_id
        string array_index
        string title
        string description
        string value
    }
    dmp_cost_cost_documentation {
        string id
        string dmp_cost_id
        string array_index
        string name
        string access_url
        string download_url
    }
    dmp_dataset {
        string id
        string dmp_id
        string array_index
        string title
        string description
        string keyword
        string type
        string general_data_format
        string geodetic_datum
        string geographic_coverage
        string data_completeness
        string issued
        string language
        string data_criticality
        string data_governance_description
        string personal_data
        string sensitive_data
        string preservation_statement
        string supported_works_url
        string data_quality_assurance
        string disclaimer
        string disposition_completed
        string dataset_is_reused
        string mulitple_language
    }
    dmp_dataset_collection {
        string id
        string dmp_dataset_id
        string description
        string data_earliest_date
        string data_latest_date
        string dataset_update_frequency
        string dataset_last_updated
        string dataset_size
        string dataset_size_units
        string growth_annual_terabytes
        string growth_end_date
    }
    dmp_dataset_creator {
        string id
        string dmp_dataset_id
        string array_index
        string mbox
        string name
    }
    dmp_dataset_creator_affiliation {
        string id
        string dmp_dataset_creator_id
        string array_index
        string creator_affiliation_name
    }
    dmp_dataset_creator_affiliation_creator_affiliation_id {
        string id
        string dmp_dataset_creator_affiliation_id
        string registry_url
        string registry_version
        string type
        string identifier
    }
    dmp_dataset_creator_affiliation_creator_country {
        string id
        string dmp_dataset_creator_affiliation_id
        string code
        string name
    }
    dmp_dataset_creator_affiliation_creator_province_state {
        string id
        string dmp_dataset_creator_affiliation_id
        string code
        string name
    }
    dmp_dataset_creator_creator_id {
        string id
        string dmp_dataset_creator_id
        string identifier
        string registry_url
        string registry_version
        string type
    }
    dmp_dataset_dataset_documentation {
        string id
        string dmp_dataset_id
        string array_index
        string name
        string description
        string access_url
        string download_url
    }
    dmp_dataset_dataset_id {
        string id
        string dmp_dataset_id
        string identifier
        string type
        string registry_url
        string registry_version
    }
    dmp_dataset_disposition_action {
        string id
        string dmp_dataset_id
        string array_index
        string type
        string description
        string authorization
        string date
    }
    dmp_dataset_disposition_planning {
        string id
        string dmp_dataset_id
        string retention_schedule_url
        string archival_value
        string archival_value_description
        string disposition_planning_last_reviewed
        string disposition_review_next
    }
    dmp_dataset_disposition_planning_disposition_impediment {
        string id
        string dmp_dataset_disposition_planning_id
        string array_index
        string type
        string description
    }
    dmp_dataset_disposition_planning_retention_specification {
        string id
        string dmp_dataset_disposition_planning_id
        string array_index
        string description
        string trigger_type
        string trigger_description
        string retention_rationale
        string retention_period_duration
        string retention_period_end_date
        string required_perpetual_use
        string required_destruction
        string trigger_occured
    }
    dmp_dataset_distribution {
        string id
        string dmp_dataset_id
        string array_index
        string title
        string description
        string created
        string issued
        string update_frequency
        string status
        string status_description
        string available_until
        string start_date
        string end_date
        string spatial_representation_type
        string character_encoding_standard
        string character_unicode_block_code
        string character_unicode_block_name
        string quality_control_level
        string data_access
        string linked_data_star_rating
        string openness_other_rating
        string openness_other_rating_system
        string protection_level
        string security_classification_level
        string data_security_privacy_measures
        string preservation_flag
        string disposition_completed
        string format
        string file_path
        string access_url
        string download_url
        string byte_size
        string data_size
        string data_size_units
    }
    dmp_dataset_distribution_data_integrity {
        string id
        string dmp_dataset_distribution_id
        string output
        string function_name
        string perfomed
        string notes
    }
    dmp_dataset_distribution_distribution_id {
        string id
        string dmp_dataset_distribution_id
        string type
        string registry_url
        string registry_version
        string identifier
    }
    dmp_dataset_distribution_geographic_bounding_box {
        string id
        string dmp_dataset_distribution_id
        string north
        string east
        string south
        string west
    }
    dmp_dataset_distribution_host {
        string id
        string dmp_dataset_distribution_id
        string title
        string description
        string url
        string storage_type
        string pid_system
        string support_checksum
        string data_priority
        string availability
        string backup_frequency
        string backup_type
        string certified_with
        string data_transfer_maximum_latency
        string data_transfer_minimum_throughput
        string geo_location
        string protocol
        string content_type
        string format
        string language
        string type
        string version
    }
    dmp_dataset_distribution_online_service {
        string id
        string dmp_dataset_distribution_id
        string array_index
        string protocol
        string service_language
        string service_url
        string name
        string content_type
        string format
        string language
    }
    dmp_dataset_distribution_physical_data_asset {
        string id
        string dmp_dataset_distribution_id
        string array_index
        string description
        string type
        string building_city
        string building_name
        string building_room_number
        string name
    }
    dmp_dataset_distribution_version_history {
        string id
        string dmp_dataset_distribution_id
        string revision_date
        string revision_description
        string revision_documentation
    }
    dmp_dataset_intellectual_property {
        string id
        string dmp_dataset_id
        string copyright_description
        string copyright_extent
        string copyright_holder
        string other
    }
    dmp_dataset_metadata {
        string id
        string dmp_dataset_id
        string array_index
        string description
        string language
    }
    dmp_dataset_metadata_metadata_standard_id {
        string id
        string dmp_dataset_metadata_id
        string type
        string registry_url
        string registry_version
        string identifier
    }
    dmp_dataset_security_and_privacy {
        string id
        string dmp_dataset_id
        string array_index
        string title
        string description
    }
    dmp_dataset_security_and_privacy_privacy_impact_assessment {
        string id
        string dmp_dataset_security_and_privacy_id
        string download_url
        string required
    }
    dmp_dataset_subject {
        string id
        string dmp_dataset_id
        string array_index
        string heading_name
        string heading_uri
        string scheme_name
        string scheme_uri
        string scheme_version
    }
    dmp_dataset_technical_resource {
        string id
        string dmp_dataset_id
        string array_index
        string name
        string description
    }
    dmp_dataset_technical_resource_data_management_system {
        string id
        string dmp_dataset_technical_resource_id
        string description
        string pid_system
        string support_checksum
        string support_versioning
        string availability
        string backup_frequency
        string backup_type
        string certified_with
        string geo_location
        string protocol
        string access_url
        string authentication
        string visibility
        string version
        string type
        string title
        string storage_type
        string compliance_standards
        string data_transfer_maximum_latency
        string data_transfer_minimum_throughput
    }
    dmp_dataset_technical_resource_hardware_requirements {
        string id
        string dmp_dataset_technical_resource_id
        string minimum_cpu_cores
        string minimum_cpu_speed
        string machine_type
        string data_processing_minimum_ram_gb
        string processing_unit_requirements
        string storage_capacity
        string description
        string network_requirements
        string title
    }
    dmp_dataset_technical_resource_software {
        string id
        string dmp_dataset_technical_resource_id
        string array_index
        string description
        string download_url
        string license
        string programming_language
        string proprietary_software
        string operating_system_name
        string operating_system_description
        string code_repository
        string execution_environment
        string dependencies
    }
    dmp_dataset_technical_resource_software_software_management_pla {
        string id
        string dmp_dataset_technical_resource_software_id
        string array_index
        string name
        string access_url
        string download_url
    }
    dmp_general_info {
        string id
        string dmp_id
        string title
        string description
        string created
        string modified
        string language
        string access
        string protection_level
        string protection_level_other_nomenclature
        string protection_level_other_level
        string security_classification_level
        string security_classification_level_other_nomenclature
        string security_classification_level_other_level
        string schema_version
        string schema_version_uri
        string ethical_issues_exist
        string ethical_issues_description
        string ethical_issues_report
    }
    dmp_general_info_dmp_id {
        string id
        string dmp_general_info_id
        string type
        string registry_uri
        string registry_version
        string identifier
    }
    dmp_general_info_linked_dmp {
        string id
        string dmp_general_info_id
        string array_index
        string relationship
        string access_url
        string download_url
    }
    dmp_general_info_linked_dmp_linked_dmp_id {
        string id
        string dmp_general_info_linked_dmp_id
        string array_index
        string type
        string registry_uri
        string registry_version
        string identifier
    }
    dmp_indigenous_considerations {
        string id
        string dmp_id
        string exist
        string group_identification
        string government_name
        string language
        string characters
        string research_method
        string indian_band_name
        string indian_band_number
    }
    dmp_indigenous_considerations_community_approval {
        string id
        string dmp_indigenous_considerations_id
        string array_index
        string status
    }
    dmp_project {
        string id
        string dmp_id
        string array_index
        string title
        string description
        string start
        string end
        string succession_plan
        string algorithmic_impact_assessment_conducted
        string algorithmic_impact_assessment_conducted_url
        string classification_plan_code
    }
    dmp_project_funding {
        string id
        string dmp_project_id
        string array_index
        string funding_status
    }
    dmp_project_funding_funder_id {
        string id
        string dmp_project_funding_id
        string type
        string registry_uri
        string registry_version
        string identifier
    }
    dmp_project_funding_grant_id {
        string id
        string dmp_project_funding_id
        string type
        string registry_uri
        string registry_version
        string identifier
    }
    dmp_project_funding_source {
        string id
        string dmp_project_funding_id
        string array_index
        string type
        string description
    }
    dmp_project_partner_organization {
        string id
        string dmp_project_id
        string array_index
        string name
    }
    dmp_project_partner_organization_agreement {
        string id
        string dmp_project_partner_organization_id
        string description
        string type
        string agreement_download_url
    }
    dmp_project_partner_organization_partner_organization_id {
        string id
        string dmp_project_partner_organization_id
        string type
        string registry_uri
        string registry_version
        string identifier
    }
    dmp_project_safeguarding_science_measures {
        string id
        string dmp_project_id
        string exist
        string redundant_backups_exist
    }